export const GET_TRANSACTION_REQUEST = "GET_TRANSACTION_REQUEST";
export const GET_TRANSACTION_SUCCESS = "GET_TRANSACTION_SUCCESS";
export const GET_TRANSACTION_FAILURE = "GET_TRANSACTION_FAILURE";

export const SEND_COIN_REQUEST = "SEND_COIN_REQUEST";
export const SEND_COIN_SUCCESS = "SEND_COIN_SUCCESS";
export const SEND_COIN_FAILURE = "SEND_COIN_FAILURE";
