export const GET_BLOCKCHAIN_REQUEST = "GET_BLOCKCHAIN_REQUEST";
export const GET_BLOCKCHAIN_SUCCESS = "GET_BLOCKCHAIN_SUCCESS";
export const GET_BLOCKCHAIN_FAILURE = "GET_BLOCKCHAIN_FAILURE";

export const GET_WALLET_REQUEST = "GET_WALLET_REQUEST";
export const GET_WALLET_SUCCESS = "GET_WALLET_SUCCESS";
export const GET_WALLET_FAILURE = "GET_WALLET_FAILURE";
