export const GET_PUZZLE_REQUEST = "GET_PUZZLE_REQUEST";
export const GET_PUZZLE_SUCCESS = "GET_PUZZLE_SUCCESS";
export const GET_PUZZLE_FAILURE = "GET_PUZZLE_FAILURE";


export const CREATE_PUZZLE_REQUEST = "CREATE_PUZZLE_REQUEST";
export const CREATE_PUZZLE_SUCCESS = "CREATE_PUZZLE_SUCCESS";
export const CREATE_PUZZLE_FAILURE = "CREATE_PUZZLE_FAILURE";

export const RESET_RECENT_PUZZLE = "RESET_RECENT_PUZZLE";

export const SOLVE_PUZZLE_REQUEST = "SOLVE_PUZZLE_REQUEST";
export const SOLVE_PUZZLE_SUCCESS = "SOLVE_PUZZLE_SUCCESS";
export const SOLVE_PUZZLE_FAILURE = "SOLVE_PUZZLE_FAILURE";


export const SELECT_PUZZLE = "SELECT_PUZZLE";
