export const LOGIN_DEVICE_REQUEST = "LOGIN_DEVICE_REQUEST";
export const LOGIN_DEVICE_SUCCESS = "LOGIN_DEVICE_SUCCESS";
export const LOGIN_DEVICE_FAILURE = "LOGIN_DEVICE_FAILURE";

export const SIGNUP_DEVICE_REQUEST = "SIGNUP_DEVICE_REQUEST";
export const SIGNUP_DEVICE_SUCCESS = "SIGNUP_DEVICE_SUCCESS";
export const SIGNUP_DEVICE_FAILURE = "SIGNUP_DEVICE_FAILURE";